#page title
page_title                                : Time & Pour                               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6747262933                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Time & Pour                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Brew better coffee. Every. Time.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Slayter Development                
your_link                                 : https://timeandpour.app                     
your_city                                 :                    
email_address                             : support@slayterdev.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : accidentallatte
twitter_username                          : 
github_username                           : SlayterDev
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Interactive Brew Timer
    description                           : Brew better coffee with our interactive brew timer. Set your grind size, water temperature, and more.
    fontawesome_icon_name                 : hourglass-half
    
  - title                                 : Built-in Recipes
    description                           : Choose from several built-in recipes for different brew methods, including V60, AeroPress, and more.
    fontawesome_icon_name                 : book-open

  - title                                 : Custom Recipe Builder
    description                           : Put together your perfect recipe step by step down to the second.
    fontawesome_icon_name                 : cogs

  - title                                 : Flavor Wheel and Journal
    description                           : Use the flavor wheel to examine your coffee and keep a journal of your brews.
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Analytics and Trends
    description                           : Track your brewing habits and see how your coffee quality changes over time.
    fontawesome_icon_name                 : chart-line
  
  - title                                 : AI Feedback
    description                           : Get AI-generated feedback on your brews to improve your coffee-making skills.
    fontawesome_icon_name                 : robot

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#f5f5f5"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#E8D8B0DD"

app_title_color                           : "#f5f5f5"
app_price_color                           : "#f5f5f5"
app_description_color                     : "#f5f5f5"

feature_title_color                       : "#f5f5f5"
feature_text_color                        : "#EBEBF599"

feature_icons_foreground_color            : "#E8D8B0"
feature_icons_background_color            : "#1c1c1e"

social_icons_foreground_color             : "#ebebf599"
social_icons_background_color             : "#2c2c2e"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
